### ISSUE TITLE
安装后提示hermes.h not found

### ISSUE THREAD

**Issue by qilovehua** [react-native-oh-library/react-native-harmony-reanimated#16]
### 描述 / Description

In file included from /Users/linhuaqi/react/cunzhijiapphm/node_modules/react-native-reanimated/Common/cpp/ReanimatedRuntime/ReanimatedHermesRuntime.cpp:1:
/Users/linhuaqi/react/cunzhijiapphm/harmony/entry/src/main/cpp/../../../../../node_modules/react-native-reanimated/Common/cpp/ReanimatedRuntime/ReanimatedHermesRuntime.h:27:10: fatal error: 'hermes/hermes.h' file not found
#include <hermes/hermes.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

### 复现步骤 / Steps to reproduce

1. 安装
    "@react-native-oh-tpl/elements": "^1.3.21-0.1.4",
    "@react-native-oh-tpl/masked-view": "file:../harmony_tgz/react-native-oh-tpl-masked-view-0.2.9-0.2.3-rc.1.tgz",
    "@react-native-oh-tpl/native-stack": "file:../harmony_tgz/react-native-oh-tpl-native-stack-6.9.26-0.0.2.tgz",
    "@react-native-oh-tpl/react-native-gesture-handler": "file:../harmony_tgz/react-native-oh-tpl-react-native-gesture-handler-2.14.13.tgz",
    "@react-native-oh-tpl/react-native-reanimated": "file:../harmony_tgz/react-native-oh-tpl-react-native-reanimated-3.6.3.tgz",
    "@react-native-oh-tpl/react-native-safe-area-context": "file:../harmony_tgz/react-native-oh-tpl-react-native-safe-area-context-4.7.4-0.1.7-rc.1.tgz",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/core": "^6.4.17",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/routers": "^6.1.9",
    "react-native-screens": "^3.29.0",
    "@rnoh/react-native-harmony-cli": "file:../react-native-harmony-cli/rnoh-react-native-harmony-cli-0.0.26.tgz",
    "react-native": "0.72.5",
    "react-native-harmony": "file:../react-native-harmony/rnoh-react-native-harmony-0.72.32.tgz",

    oh-package.json5
   "@rnoh/react-native-openharmony": "file:../libs/react_native_openharmony_release-5.0.0.500.har",

2. DevEco-Studio运行entry报错

### 库版本 / Library version

5.0.0.500

### React Native OpenHarmony version

0.72.29

### 构建类型 / Build type

Release app & dev bundle

### 设备 / Device

None

### 已悉知 / Acknowledgements

Yes

**Comment by qilovehua** [comment]
把路径进到CMakeLists.txt即可

**Comment by 1813549429** [comment]
你好，我也碰到了这个问题。请问下具体输入哪个路径呢
@qilovehua

**Comment by qilovehua** [comment]
> 你好，我也碰到了这个问题。请问下具体输入哪个路径呢 [@qilovehua](https://github.com/qilovehua)

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/2cc30d5d-6cde-4f27-a49c-75b3ee0bf4b4" />

可以在third-party下面搜索下hermes.h文件看看有没有

**Comment by 1813549429** [comment]
> > 你好，我也听出了这个问题。请问下具体输入哪个路径呢[@qilovehua](https://github.com/qilovehua)
> 
> <img alt="图像" width="959" src="https://private-user-images.githubusercontent.com/12076175/410277002-2cc30d5d-6cde-4f27-a49c-75b3ee0bf4b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4MTM5NTYsIm5iZiI6MTczODgxMzY1NiwicGF0aCI6Ii8xMjA3NjE3NS80MTAyNzcwMDItMmNjMzBkNWQtNmNkZS00ZjI3LWE0OWMtNzViM2VlMGJmNGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA2VDAzNDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjNhN2RiZTYxNDU2NzA3MDZlZmNmYmU0OGI2NjMzYTE3YTI3ZjUzMTBhMjM0NjVjMjU1ZWYxNWMwNzg1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HzQJIZjEIjCeC5D5Y95I6DGMHF5NEpKFmXN3XQQEoOQ">
> 可以在第三方下面搜索下hermes.h文件看看有没有

可以了，太强了哥。帮上我大忙了，太感谢了
